apiVersion: v1
kind: Pod
metadata:
  name: numa-aware-pod
  annotations:
    # Bind to CPU 0,1,2,3
    cpu-set: "0-3"
    # Additional NUMA annotations
    numa-node: "0"
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        cpu: "2"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "1Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: numa-aware-pod-advanced
  annotations:
    # Bind to specific CPUs on different NUMA nodes
    cpu-set: "0,2,8,10"
    # Specify NUMA nodes
    numa-node: "0,1"
spec:
  containers:
  - name: app
    image: redis:latest
    resources:
      requests:
        cpu: "4"
        memory: "2Gi"
      limits:
        cpu: "4"
        memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numa-aware-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: numa-aware-app
  template:
    metadata:
      labels:
        app: numa-aware-app
      annotations:
        # Different CPU affinity for different pods
        cpu-set: "4-7"
        numa-node: "1"
    spec:
      containers:
      - name: app
        image: nginx:latest
        resources:
          requests:
            cpu: "2"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "512Mi"